defaults:
  - _self_

models:
  detection: "runs/detect/runs/detect_v2/yolov10s/weights/best.pt"
  ocr: "mlartifacts/ocr_v3/crnn-epoch=03-val_cer=0.0080.ckpt"

ocr:
  img_h: 64
  img_w: 160
  alphabet: "0123456789ABEKMHOPCTYX_"
  pad_idx: 22

detection:
  conf_threshold: 0.1

server:
  host: "0.0.0.0"
  port: 50051
