defaults:
  - _self_

models:
  detection: "runs/baseline/weights/best.pt"
  ocr: "mlartifacts/ocr/ocr-v1-epoch=06-val_acc=0.9588.ckpt"

ocr:
  img_h: 32
  img_w: 128
  alphabet: "0123456789ABEKMHOPCTYX_"
  pad_idx: 22

detection:
  conf_threshold: 0.1

server:
  host: "0.0.0.0"
  port: 50051
