// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: ml_car_plate_recognition.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_ml_car_plate_recognition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_car_plate_recognition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_ml_car_plate_recognition_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type PlateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlateNumber   string                 `protobuf:"bytes,1,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Bbox          *BoundingBox           `protobuf:"bytes,3,opt,name=bbox,proto3" json:"bbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlateResult) Reset() {
	*x = PlateResult{}
	mi := &file_ml_car_plate_recognition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlateResult) ProtoMessage() {}

func (x *PlateResult) ProtoReflect() protoreflect.Message {
	mi := &file_ml_car_plate_recognition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlateResult.ProtoReflect.Descriptor instead.
func (*PlateResult) Descriptor() ([]byte, []int) {
	return file_ml_car_plate_recognition_proto_rawDescGZIP(), []int{1}
}

func (x *PlateResult) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *PlateResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PlateResult) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            int32                  `protobuf:"varint,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            int32                  `protobuf:"varint,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            int32                  `protobuf:"varint,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            int32                  `protobuf:"varint,4,opt,name=y2,proto3" json:"y2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_ml_car_plate_recognition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_ml_car_plate_recognition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_ml_car_plate_recognition_proto_rawDescGZIP(), []int{2}
}

func (x *BoundingBox) GetX1() int32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *BoundingBox) GetY1() int32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *BoundingBox) GetX2() int32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *BoundingBox) GetY2() int32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

type PredictMultiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plates        []*PlateResult         `protobuf:"bytes,1,rep,name=plates,proto3" json:"plates,omitempty"`
	TotalDetected int32                  `protobuf:"varint,2,opt,name=total_detected,json=totalDetected,proto3" json:"total_detected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictMultiResponse) Reset() {
	*x = PredictMultiResponse{}
	mi := &file_ml_car_plate_recognition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictMultiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictMultiResponse) ProtoMessage() {}

func (x *PredictMultiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_car_plate_recognition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictMultiResponse.ProtoReflect.Descriptor instead.
func (*PredictMultiResponse) Descriptor() ([]byte, []int) {
	return file_ml_car_plate_recognition_proto_rawDescGZIP(), []int{3}
}

func (x *PredictMultiResponse) GetPlates() []*PlateResult {
	if x != nil {
		return x.Plates
	}
	return nil
}

func (x *PredictMultiResponse) GetTotalDetected() int32 {
	if x != nil {
		return x.TotalDetected
	}
	return 0
}

var File_ml_car_plate_recognition_proto protoreflect.FileDescriptor

const file_ml_car_plate_recognition_proto_rawDesc = "" +
	"\n" +
	"\x1eml_car_plate_recognition.proto\x12\x02ml\"/\n" +
	"\x0ePredictRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\"u\n" +
	"\vPlateResult\x12!\n" +
	"\fplate_number\x18\x01 \x01(\tR\vplateNumber\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12#\n" +
	"\x04bbox\x18\x03 \x01(\v2\x0f.ml.BoundingBoxR\x04bbox\"M\n" +
	"\vBoundingBox\x12\x0e\n" +
	"\x02x1\x18\x01 \x01(\x05R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x02 \x01(\x05R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x03 \x01(\x05R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x04 \x01(\x05R\x02y2\"f\n" +
	"\x14PredictMultiResponse\x12'\n" +
	"\x06plates\x18\x01 \x03(\v2\x0f.ml.PlateResultR\x06plates\x12%\n" +
	"\x0etotal_detected\x18\x02 \x01(\x05R\rtotalDetected2b\n" +
	"\x1cMLCarPlateRecognitionService\x12B\n" +
	"\x12RecognizeCarPlates\x12\x12.ml.PredictRequest\x1a\x18.ml.PredictMultiResponseB.Z,github.com/ml-car-plate-recognition/proto;pbb\x06proto3"

var (
	file_ml_car_plate_recognition_proto_rawDescOnce sync.Once
	file_ml_car_plate_recognition_proto_rawDescData []byte
)

func file_ml_car_plate_recognition_proto_rawDescGZIP() []byte {
	file_ml_car_plate_recognition_proto_rawDescOnce.Do(func() {
		file_ml_car_plate_recognition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_car_plate_recognition_proto_rawDesc), len(file_ml_car_plate_recognition_proto_rawDesc)))
	})
	return file_ml_car_plate_recognition_proto_rawDescData
}

var file_ml_car_plate_recognition_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ml_car_plate_recognition_proto_goTypes = []any{
	(*PredictRequest)(nil),       // 0: ml.PredictRequest
	(*PlateResult)(nil),          // 1: ml.PlateResult
	(*BoundingBox)(nil),          // 2: ml.BoundingBox
	(*PredictMultiResponse)(nil), // 3: ml.PredictMultiResponse
}
var file_ml_car_plate_recognition_proto_depIdxs = []int32{
	2, // 0: ml.PlateResult.bbox:type_name -> ml.BoundingBox
	1, // 1: ml.PredictMultiResponse.plates:type_name -> ml.PlateResult
	0, // 2: ml.MLCarPlateRecognitionService.RecognizeCarPlates:input_type -> ml.PredictRequest
	3, // 3: ml.MLCarPlateRecognitionService.RecognizeCarPlates:output_type -> ml.PredictMultiResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ml_car_plate_recognition_proto_init() }
func file_ml_car_plate_recognition_proto_init() {
	if File_ml_car_plate_recognition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_car_plate_recognition_proto_rawDesc), len(file_ml_car_plate_recognition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_car_plate_recognition_proto_goTypes,
		DependencyIndexes: file_ml_car_plate_recognition_proto_depIdxs,
		MessageInfos:      file_ml_car_plate_recognition_proto_msgTypes,
	}.Build()
	File_ml_car_plate_recognition_proto = out.File
	file_ml_car_plate_recognition_proto_goTypes = nil
	file_ml_car_plate_recognition_proto_depIdxs = nil
}
