// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.1
// source: ml_car_plate_recognition.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MLCarPlateRecognitionService_RecognizeCarPlates_FullMethodName = "/ml.MLCarPlateRecognitionService/RecognizeCarPlates"
)

// MLCarPlateRecognitionServiceClient is the client API for MLCarPlateRecognitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MLCarPlateRecognitionServiceClient interface {
	RecognizeCarPlates(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictMultiResponse, error)
}

type mLCarPlateRecognitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLCarPlateRecognitionServiceClient(cc grpc.ClientConnInterface) MLCarPlateRecognitionServiceClient {
	return &mLCarPlateRecognitionServiceClient{cc}
}

func (c *mLCarPlateRecognitionServiceClient) RecognizeCarPlates(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictMultiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictMultiResponse)
	err := c.cc.Invoke(ctx, MLCarPlateRecognitionService_RecognizeCarPlates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLCarPlateRecognitionServiceServer is the server API for MLCarPlateRecognitionService service.
// All implementations must embed UnimplementedMLCarPlateRecognitionServiceServer
// for forward compatibility.
type MLCarPlateRecognitionServiceServer interface {
	RecognizeCarPlates(context.Context, *PredictRequest) (*PredictMultiResponse, error)
	mustEmbedUnimplementedMLCarPlateRecognitionServiceServer()
}

// UnimplementedMLCarPlateRecognitionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLCarPlateRecognitionServiceServer struct{}

func (UnimplementedMLCarPlateRecognitionServiceServer) RecognizeCarPlates(context.Context, *PredictRequest) (*PredictMultiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecognizeCarPlates not implemented")
}
func (UnimplementedMLCarPlateRecognitionServiceServer) mustEmbedUnimplementedMLCarPlateRecognitionServiceServer() {
}
func (UnimplementedMLCarPlateRecognitionServiceServer) testEmbeddedByValue() {}

// UnsafeMLCarPlateRecognitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLCarPlateRecognitionServiceServer will
// result in compilation errors.
type UnsafeMLCarPlateRecognitionServiceServer interface {
	mustEmbedUnimplementedMLCarPlateRecognitionServiceServer()
}

func RegisterMLCarPlateRecognitionServiceServer(s grpc.ServiceRegistrar, srv MLCarPlateRecognitionServiceServer) {
	// If the following call panics, it indicates UnimplementedMLCarPlateRecognitionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLCarPlateRecognitionService_ServiceDesc, srv)
}

func _MLCarPlateRecognitionService_RecognizeCarPlates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLCarPlateRecognitionServiceServer).RecognizeCarPlates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLCarPlateRecognitionService_RecognizeCarPlates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLCarPlateRecognitionServiceServer).RecognizeCarPlates(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLCarPlateRecognitionService_ServiceDesc is the grpc.ServiceDesc for MLCarPlateRecognitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLCarPlateRecognitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ml.MLCarPlateRecognitionService",
	HandlerType: (*MLCarPlateRecognitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecognizeCarPlates",
			Handler:    _MLCarPlateRecognitionService_RecognizeCarPlates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ml_car_plate_recognition.proto",
}
