// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: ml_car_plate_recognition.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_ml_car_plate_recognition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_car_plate_recognition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_ml_car_plate_recognition_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlateNumber   string                 `protobuf:"bytes,1,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_ml_car_plate_recognition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_car_plate_recognition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_ml_car_plate_recognition_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *PredictResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_ml_car_plate_recognition_proto protoreflect.FileDescriptor

const file_ml_car_plate_recognition_proto_rawDesc = "" +
	"\n" +
	"\x1eml_car_plate_recognition.proto\x12\x02ml\"/\n" +
	"\x0ePredictRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\"T\n" +
	"\x0fPredictResponse\x12!\n" +
	"\fplate_number\x18\x01 \x01(\tR\vplateNumber\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence2\\\n" +
	"\x1cMLCarPlateRecognitionService\x12<\n" +
	"\x11RecognizeCarPlate\x12\x12.ml.PredictRequest\x1a\x13.ml.PredictResponseB.Z,github.com/ml-car-plate-recognition/proto;pbb\x06proto3"

var (
	file_ml_car_plate_recognition_proto_rawDescOnce sync.Once
	file_ml_car_plate_recognition_proto_rawDescData []byte
)

func file_ml_car_plate_recognition_proto_rawDescGZIP() []byte {
	file_ml_car_plate_recognition_proto_rawDescOnce.Do(func() {
		file_ml_car_plate_recognition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_car_plate_recognition_proto_rawDesc), len(file_ml_car_plate_recognition_proto_rawDesc)))
	})
	return file_ml_car_plate_recognition_proto_rawDescData
}

var file_ml_car_plate_recognition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ml_car_plate_recognition_proto_goTypes = []any{
	(*PredictRequest)(nil),  // 0: ml.PredictRequest
	(*PredictResponse)(nil), // 1: ml.PredictResponse
}
var file_ml_car_plate_recognition_proto_depIdxs = []int32{
	0, // 0: ml.MLCarPlateRecognitionService.RecognizeCarPlate:input_type -> ml.PredictRequest
	1, // 1: ml.MLCarPlateRecognitionService.RecognizeCarPlate:output_type -> ml.PredictResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ml_car_plate_recognition_proto_init() }
func file_ml_car_plate_recognition_proto_init() {
	if File_ml_car_plate_recognition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_car_plate_recognition_proto_rawDesc), len(file_ml_car_plate_recognition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_car_plate_recognition_proto_goTypes,
		DependencyIndexes: file_ml_car_plate_recognition_proto_depIdxs,
		MessageInfos:      file_ml_car_plate_recognition_proto_msgTypes,
	}.Build()
	File_ml_car_plate_recognition_proto = out.File
	file_ml_car_plate_recognition_proto_goTypes = nil
	file_ml_car_plate_recognition_proto_depIdxs = nil
}
